import mongoose from 'mongoose';

const UmbracoDBSchema = new mongoose.Schema({
	"Gender" : Number,
	"Initial-PrimaryProblemSubstanceAmount" : Number,
	"Retention in treatment" : Number,
	"main problem" : String,
	"Ethnicity" : String,
	"Current-PrimarySubstanceStopUsing" : Number,
	"CompletedLBM" : Number,
	"Current-Diffsits0" : Number,
	"City" : String,
	"Initial-Emot0" : Number,
	"Current-Negth0" : Number,
	"DateStartUtc" : Date,
	"HasClickedChoiceInCommunity" : Number,
	"Current-PrimarySubstanceWorry" : Number,
	"Country" : String,
	"IsGrouped" : Boolean,
	"ParentDashboardName" : String,
	"Address1" : String,
	"Postcode" : String,
	"Initial-PrimaryProblemSubstanceDaysUsage" : Number,
	"Initial-AlcoholUsingDays" : Number,
	"DateEndUtc" : Date,
	"Initial-GoalAmountOfAlcohol" : Number,
	"Name of service using online or app?" :String,
	"Initial-Lifestyle0" : Number,
	"Current-PrimaryProblemSubstanceAmount" : Number,
	"CompleteEmotions1" : Number,
	"NumberOfProgressChecks" : Number,
	"TotalTimeOnline" : Number,
	"Access Code activation date" : Date,
	"IsNomsUser" : Boolean,
	"CompleteDifficultSituations1" : Number,
	"Current-PrimarySubstanceOutOfControl" : Number,
	"DashboardName" : String,
	"Current-AlcoholUnitsPerDay" : Number,
	"Current-PrimaryProblemSubstanceDaysUsage" : Number,
	"Initial-AlcoholUnitsPerDay" : Number,
	"DashboardId" : Number,
	"Initial-Behav0" : Number,
	"Initial-PrimarySubstanceAnxiousOrWorried" : Number,
	"ServiceGuid" : String,
	"Completion of EBI" : Number,
	"Current-PrimarySubstanceAnxiousOrWorried" : Number,
	"CompleteLifestyle1" : Number,
	"Reduction in alcohol" : Number,
	"Current-Phys0" : Number,
	"Age" : Number,
	"UserId" : String,
	"CompletePhysicalSensations2" : Number,
	"ParentDashboardId" : Number,
	"Access Code" : String,
	"Username" : String,
	"HasEngagedOverdosePrevention" : Boolean,
	"Initial-GoalAmountOfPrimarySubstance" : Number,
	"CompleteLifestyle2" : Number,
	"Initial-GoalNumberOfAlcoholUsingDays" : Number,
	"ServiceId" : Number,
	"Initial-Negth0" : Number,
	"Deleted" : Boolean,
	"ServiceName" : String,
	"CompleteEmotions2" : Number,
	"Initial-PrimarySubstanceWorry" : Number,
	"Code" : String,
	"BASELINE ASSESSMENT COMPLETED" : Number,
	"Current-Behav0" : Number,
	"Current-Lifestyle0" : Number,
	"Email" : String,
	"CompletePhysicalSensations1" : Number,
	"CompleteDifficultSituations2" : Number,
	"Application version" : Number,
	"CompleteNegativeThoughts2" : Number,
	"NumberOfLogins" : Number,
	"version" : String,
	"Telephone" : String,
	"Initial-GoalNumberOfPrimarySubstanceUsingDays" : Number,
	"drug type" : String,
	"Current-PrimarySubstanceGoWithout" : Number,
	"CompleteDestructiveBehaviours2" : Number,
	"Reduction in substance" : Number,
	"HasAchievedGoal" : Number,
	"Current-Emot0" : Number,
	"Initial-PrimarySubstanceGoWithout" : Number,
	"NumberOfStrategiesCompleted" : Number,
	"Initial-Phys0" : Number,
	"Initial-PrimarySubstanceOutOfControl" : Number,
	"Current-AlcoholUsingDays" : Number,
	"Initial-Diffsits0" : Number,
	"CompleteNegativeThoughts1" : Number,
	"CompleteDestructiveBehaviours1" : Number,
	"HasHadAllGreen" : Number,
	"Initial-PrimarySubstanceStopUsing" : Number

});

export default mongoose.model('UmbracoDB', UmbracoDBSchema, 'umbracodb');
